apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ required "O campo 'name' é obrigatório!" .Values.config.name }}-secret
data:
  USER: {{ .Values.config.username }}
  PASSWORD: {{ .Values.config.password }}
