apiVersion: v1
kind: Service
metadata:
  name: {{ required "O campo 'name' é obrigatório!" .Values.config.name }}-service
  namespace: {{ required "O campo 'namespace' é obrigatório!" .Values.config.namespace }}
  annotations:
    {{- toYaml .Values.Values.service.annotations | nindent 4 }}
  labels:
    app: {{ required "O campo 'name' é obrigatório!" .Values.config.name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ required "O campo 'name' é obrigatório!" .Values.config.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.ports.port | default 80 }}
      targetPort: {{ .Values.service.ports.targetPort | default 3000 }}
      name: {{ .Values.service.ports.name | default http }}
