---
{{- if .Values.ingress.internal.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.ingress.internal.annotations | nindent 4 }}
  name: {{ required "O campo 'name' é obrigatório!" .Values.config.name }}-ingress
  namespace: {{ .Values.config.namespace }}
spec:
  ingressClassName: {{ .Values.ingress.internal.ingressClassName | default "nginx" }}
  rules:
  - host: {{ required "O campo 'host' é obrigatório!" .Values.ingress.internal.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ required "O campo 'name' é obrigatório!" .Values.config.name }}-service
            port:
              name: {{ .Values.service.ports.name | default "http" }}
        path: /
        pathType: Prefix
  {{- if .Values.ingress.internal.tls.enabled }}
  tls:
  - hosts:
    - {{ required "O campo 'host' é obrigatório!" .Values.ingress.internal.host }}
    secretName: {{ required "O campo 'secretCertificate' é obrigatório!" .Values.ingress.internal.tls.secretCertificate  }}
  {{- end }}
{{- end }}
