---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "O campo 'name' é obrigatório!" .Values.config.name }}-secret
stringData:
  config.json: |
    {
      "ARGO_URL": "{{ required "O campo 'argoUrl' é obrigatório!" .Values.config.argoUrl }}",
      "ARGO_USER": "{{ required "O campo 'username' é obrigatório!" .Values.config.username }}",
      "ARGO_PASSWORD": "{{ required "O campo 'password' é obrigatório!" .Values.config.password }}",
      "APP_LIST": {{ required "O campo 'applicationsList' é obrigatório!" .Values.config.applicationsList | quote }}
    }
type: Opaque
