---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "O campo 'name' é obrigatório!" .Values.config.name }}-secret
data:
  config.json: |
    {
      "ARGO_URL": "{{ required "O campo 'argoUrl' é obrigatório!" .Values.config.argoUrl | b64enc }}",
      "ARGO_USER": "{{ required "O campo 'username' é obrigatório!" .Values.config.username | b64enc }}",
      "ARGO_PASSWORD": "{{ required "O campo 'password' é obrigatório!" .Values.config.password | b64enc }}",
      "APP_LIST": "{{ required "O campo 'applicationsList' é obrigatório!" .Values.config.applicationsList  | b64enc  }}"
    }
type: Opaque
